(()=>{'use strict';
const TEST='https://vylrliliaojtcrrhvscv.supabase.co',operator=document.body.dataset.mode==='operator';
const $=s=>document.querySelector(s),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const message=(s,error=false)=>{const m=$('#message');m.textContent=s;m.hidden=!s;m.className=error?'error':'';};
if(SUPABASE_URL!==TEST){message('Esta página necesita la conexión TEST correcta. No se enviará información.',true);document.querySelectorAll('button').forEach(b=>b.disabled=true);return;}
const client=window.supabase.createClient(TEST,SUPABASE_ANON_KEY),bridge=operator&&window.SemblanziaPlaneaBridge?window.SemblanziaPlaneaBridge.create(client):null;let active=null,selection=null,loadVersion=0;const retryKeys=new Map();
const states={submitted:'Solicitud recibida',sourcing:'Buscando opciones',awaiting_quotes:'Recibiendo propuestas',comparison_ready:'Tus opciones están listas',connected:'Conexión solicitada',cancelled:'Cancelada',draft:'Borrador'};
const events={wedding:'Boda',sweet15:'XV años',birthday:'Cumpleaños',graduation:'Graduación',baptism:'Bautizo',other:'Celebración'};
const serviceSelect=$('#service-category'),serviceOther=$('#service-category-other');
if(serviceSelect&&serviceOther){const syncService=()=>{const other=serviceSelect.value==='Otro';serviceOther.hidden=!other;serviceOther.required=other;if(!other)serviceOther.value='';};serviceSelect.addEventListener('change',syncService);syncService();}
const taskLabels={source_providers:'Buscar proveedores',verify_providers:'Verificar proveedores',prepare_comparison:'Preparar comparación',review_quote:'Revisar propuesta',follow_up_connection:'Dar seguimiento a conexión'};
function dateMX(value){if(!value)return 'Fecha por definir';const p=String(value).split('-').map(Number);if(p.length!==3||!p[0]||!p[1]||!p[2])return value;return new Intl.DateTimeFormat('es-MX',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(Date.UTC(p[0],p[1]-1,p[2])));}
function shortRef(id){return id?'#'+String(id).replace(/-/g,'').slice(0,8).toUpperCase():'';}
const labels={SIGN_IN_REQUIRED:'Inicia sesión para continuar.',OPERATOR_REQUIRED:'Tu cuenta no tiene acceso a operaciones.',REQUEST_NOT_FOUND:'No encontramos esta solicitud en tu cuenta.',EXPLICIT_CONTACT_CONSENT_REQUIRED:'Confirma que deseas solicitar el contacto.',OFFER_REVIEW_REQUIRED:'Confirma que revisaste la oferta.',CONNECTION_PREREQUISITES_NOT_MET:'La oferta cambió. Actualiza tus opciones antes de continuar.',COMPARISON_NOT_AVAILABLE:'Esta comparación ya no está disponible.',IDEMPOTENCY_CONFLICT:'La operación cambió. Actualiza la página y vuelve a intentar.',TASK_ALREADY_CLAIMED:'Otro operador está atendiendo esta tarea.'};
async function rpc(name,args){const {data,error}=await client.rpc(name,args);if(error)throw new Error(labels[error.message]||error.message);return data;}
function formData(form){return Object.fromEntries(new FormData(form));}
async function run(fn){message('');try{await fn();}catch(e){message(e.message||'No pudimos completar esta acción.',true);}}
async function lock(form,fn){const controls=[...form.querySelectorAll('button')];controls.forEach(b=>b.disabled=true);try{await fn();}finally{controls.forEach(b=>b.disabled=false);}}
function keyFor(name,data){const fingerprint=name+JSON.stringify(data);if(!retryKeys.has(fingerprint))retryKeys.set(fingerprint,crypto.randomUUID());return {fingerprint,key:retryKeys.get(fingerprint)};}
async function action(name,data){const retry=keyFor(name,{request:active,data});await rpc('planea_operator_action',{p_action:name,p_request:active,p_data:data,p_key:retry.key});retryKeys.delete(retry.fingerprint);await detail(active);await refresh();}
async function refresh(){const rows=await rpc('planea_list_requests',{p_operator:operator});$('#requests').innerHTML=rows.length?rows.map(r=>`<article class="card request"><div><strong>${escape(r.service_category)}</strong><p>${escape(events[r.request_data.event_type]||r.request_data.event_type)} · ${escape(r.request_data.location)}${r.request_data.event_date?' · '+escape(dateMX(r.request_data.event_date)):''}</p><span class="status">${escape(states[r.status]||r.status)}</span></div><button class="secondary" data-request="${r.id}">${operator?'Atender solicitud':'Ver mi solicitud'}</button></article>`).join(''):'<p>Aún no hay solicitudes. Tu próxima idea empieza aquí.</p>';$('#requests').querySelectorAll('[data-request]').forEach(b=>b.addEventListener('click',()=>run(()=>detail(b.dataset.request))));}
function context(r){const req=r.request_data||{},requirements=String(req.requirements||'').trim(),notes=String(req.notes||'').trim();return `<p>${escape(events[req.event_type]||req.event_type)} · ${escape(req.location)} · ${escape(dateMX(req.event_date))}</p>${requirements?`<div class="request-field"><b>Qué te gustaría incluir</b><p>${escape(requirements)}</p></div>`:''}${notes?`<div class="request-field"><b>Algo más que debamos saber</b><p>${escape(notes)}</p></div>`:''}<span class="status">${escape(states[r.status]||r.status)}</span>`;}
async function detail(id){const version=++loadVersion;const data=await rpc('planea_get_request',{p_request:id,p_operator:operator});if(version!==loadVersion)return;active=id;selection=null;const el=$('#detail');el.hidden=false;if(operator){await renderOperations(data);}else{renderCustomer(data);}el.scrollIntoView({behavior:'smooth',block:'start'});}
function renderCustomer(data){const {request:r}=data;let html=`<article class="card"><h2>Tu solicitud de ${escape(r.service_category)}</h2>${context(r)}`;
if(data.connections.length){html+='<h3>Ya solicitaste la conexión.</h3><p>Semblanzia coordinará el contacto con el proveedor que elegiste. No se realizó ningún cobro en esta prueba.</p>';}
else if(data.comparisons.length){const c=data.comparisons[0];html+='<h3>Compara tus opciones</h3><p>Revisa qué incluye cada propuesta. Elegir una oferta todavía no solicita el contacto.</p>'+ (c.comparison_data.note?`<p>${escape(c.comparison_data.note)}</p>`:'')+'<div class="offers">';for(const offer of c.comparison_data.offers){html+=`<article class="offer"><h3>${escape(offer.provider_name)}</h3><p class="price">${new Intl.NumberFormat('es-MX',{style:'currency',currency:offer.currency}).format(offer.amount)}</p><p>${escape(offer.offer.summary)}</p>${offer.offer.inclusions?`<p><b>Incluye:</b> ${escape(offer.offer.inclusions)}</p>`:''}${offer.offer.exclusions?`<p><b>No incluye:</b> ${escape(offer.offer.exclusions)}</p>`:''}${offer.offer.valid_until?`<p>Vigencia: ${escape(offer.offer.valid_until)}</p>`:''}${offer.offer.terms?`<p>${escape(offer.offer.terms)}</p>`:''}<label class="check"><input type="checkbox" data-review="${offer.quote_id}">He revisado esta oferta.</label><button data-select="${offer.quote_id}" data-comparison="${c.id}">Elegir esta oferta</button></article>`;}html+='</div><div id="consent" hidden><h3>¿Quieres que te conectemos?</h3><p id="chosen"></p><label class="check"><input id="contact-consent" type="checkbox">Solicito y autorizo que Semblanzia me conecte con el proveedor de la oferta elegida.</label><button id="connect">Solicitar conexión</button><p class="muted">Esta autorización se guarda junto con tu selección.</p></div>';}
else html+='<h3>Estamos preparando el siguiente paso.</h3><p>Aquí recibirás las propuestas cuando estén listas para compararlas.</p>';
$('#detail').innerHTML=html+'</article>';
$('#detail').querySelectorAll('[data-select]').forEach(b=>b.addEventListener('click',()=>run(async()=>{if(!$('#detail').querySelector(`[data-review="${b.dataset.select}"]`).checked)throw new Error('Confirma que revisaste la oferta que quieres elegir.');await lock(b.closest('article'),async()=>{selection=await rpc('planea_select_offer',{p_comparison:b.dataset.comparison,p_quote:b.dataset.select,p_reviewed:true});$('#consent').hidden=false;$('#contact-consent').checked=false;$('#chosen').textContent='Elegiste '+b.closest('article').querySelector('h3').textContent+'.';$('#consent').scrollIntoView({behavior:'smooth'});message('Oferta elegida. El contacto requiere tu autorización expresa.');});})));
if($('#connect'))$('#connect').addEventListener('click',()=>run(async()=>{if(!$('#contact-consent').checked)throw new Error('Marca la autorización de contacto para solicitar la conexión.');await lock($('#consent'),async()=>{await rpc('planea_request_connection',{p_selection:selection,p_consent:true});await detail(active);await refresh();message('Tu conexión quedó solicitada. Semblanzia te acompañará en el siguiente paso.');});}));}
function options(rows,label){return rows.map(x=>`<option value="${x.id}">${escape(label(x))}</option>`).join('');}
async function renderOperations(d){
 const r=d.request,closed=['connected','cancelled'].includes(r.status);
 let html=`<article class="card request-focus"><div class="section-head"><div><p class="eyebrow">SOLICITUD ${escape(shortRef(r.id))}</p><h2>${escape(r.service_category)}</h2></div><span class="status">${escape(states[r.status]||r.status)}</span></div>${context(r)}</article>`;
 if(!closed){
  html+=`<section class="card bridge-card"><p class="eyebrow">PASO 1 · BUSCAR OPCIONES</p><h3>Preparar búsqueda con ChatGPT</h3><p>Semblanzia genera un paquete sin identidad del cliente y con la información necesaria para buscar proveedores.</p><div class="bridge-actions"><label>Opciones a buscar<select id="provider-count"><option value="3">3 proveedores</option><option value="5">5 proveedores</option><option value="7">7 proveedores</option></select></label><button id="copy-sourcing">Copiar para ChatGPT</button></div><p class="muted">Un clic. No necesitas reconstruir la solicitud ni copiar datos internos.</p></section>`;
  html+=`<section class="card bridge-card"><p class="eyebrow">PASO 2 · PROVEEDORES ENCONTRADOS</p><h3>Importar proveedores encontrados</h3><p>Pega el paquete <code>planea.provider_candidates.v1</code> devuelto por la búsqueda. Semblanzia valida privacidad, evidencia y procedencia, evita duplicados y crea automáticamente el siguiente paso: Verificar proveedores.</p><form id="candidate-import"><label>Paquete de proveedores<textarea name="package" class="bridge-paste" required placeholder="Pega aquí el paquete JSON planea.provider_candidates.v1"></textarea></label><button>Importar proveedores</button></form><div id="candidate-import-result"></div></section>`;
  html+=`<section class="card bridge-card"><p class="eyebrow">PASO 3 · RECIBIR PROPUESTA</p><h3>Importar propuesta del proveedor</h3><p>Después de verificar y contactar al proveedor, la respuesta estructurada podrá importarse aquí. En M2A no se envía ningún contacto automáticamente.</p><form id="bridge-import"><label>Paquete de propuesta<textarea name="package" class="bridge-paste" required placeholder="Pega aquí el paquete JSON generado por ChatGPT"></textarea></label><label class="check"><input name="reviewed" type="checkbox">Revisé la información del proveedor y la propuesta.</label><button>Importar propuesta</button></form><div id="import-result"></div></section>`;
 }
 html+=`<section class="card"><h3>Propuestas recibidas</h3>${d.quotes.length?d.quotes.map(q=>`<div class="proposal-row"><b>${escape(d.candidates.find(c=>c.provider_id===q.provider_id)?.provider.business_name||'Proveedor')}</b><span>${q.amount==null?'Precio por revisar':escape(q.amount)+' '+escape(q.currency)}</span><span class="status">${escape(q.status==='eligible'?'Lista para comparar':'Requiere revisión')}</span><p>${escape(q.structured_offer?.summary||'')}</p></div>`).join(''):'<p>Aún no hay propuestas importadas.</p>'}`;
 const eligible=d.quotes.filter(q=>q.status==='eligible');
 if(!closed&&eligible.length)html+=`<details><summary>Preparar comparación para el cliente</summary><form id="comparison">${eligible.map(q=>`<label class="check"><input type="checkbox" name="quote_ids" value="${q.id}">${escape(d.candidates.find(c=>c.provider_id===q.provider_id)?.provider.business_name||'Proveedor')} · ${escape(q.amount)} ${escape(q.currency)}</label>`).join('')}<label>Nota para el cliente<textarea name="note"></textarea></label><label class="check"><input type="checkbox" name="publish">Publicar ahora para el cliente</label><button>Preparar comparación</button></form></details>`;
 html+=d.comparisons.map(c=>`<p>Comparación ${escape(c.status==='published'?'publicada':'en preparación')} · ${c.comparison_data.offers.length} ofertas ${!closed&&c.status==='draft'?`<button data-publish="${c.id}" class="secondary">Publicar</button>`:''}</p>`).join('')+'</section>';
 const exceptions=d.tasks.filter(t=>!['completed','cancelled'].includes(t.status));
 if(exceptions.length)html+=`<details class="card"><summary>Excepciones y pendientes (${exceptions.length})</summary>${exceptions.map(t=>`<p><b>${escape(taskLabels[t.task_type]||'Revisión pendiente')}</b> · ${escape(t.status==='in_progress'?'En curso':t.status==='queued'?'Pendiente':t.status)}</p>`).join('')}</details>`;
 $('#detail').innerHTML=html;
 if($('#copy-sourcing'))$('#copy-sourcing').addEventListener('click',()=>run(async()=>{if(!bridge)throw new Error('El puente IA de TEST no está disponible.');const b=$('#copy-sourcing'),count=Number($('#provider-count').value);b.disabled=true;try{const text=await bridge.copyText(active,count);await navigator.clipboard.writeText(text);message('Paquete de búsqueda copiado. Pégalo en ChatGPT para buscar y preparar el contacto con proveedores.');}catch(e){throw e;}finally{b.disabled=false;}}));
 if($('#candidate-import'))$('#candidate-import').addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget;run(()=>lock(f,async()=>{let pkg;try{pkg=JSON.parse(f.elements.package.value);}catch(_){throw new Error('El paquete de proveedores no contiene JSON válido.');}const receipt=await rpc('planea_import_provider_candidates_v1',{p_request:active,p_package:pkg});$('#candidate-import-result').innerHTML=`<div class="import-receipt"><b>Proveedores importados.</b><p>${escape(receipt.candidate_count)} candidato(s) registrados. Siguiente paso: Verificar proveedores.</p></div>`;f.elements.package.value='';await detail(active);await refresh();message('Proveedores importados. PLANEA creó automáticamente el paso Verificar proveedores.');}));});
 if($('#bridge-import'))$('#bridge-import').addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget;run(()=>lock(f,async()=>{if(!bridge)throw new Error('El puente IA de TEST no está disponible.');const receipt=await bridge.importQuote(active,f.elements.package.value,f.elements.reviewed.checked);const missing=receipt.missing_fields||[];$('#import-result').innerHTML=`<div class="import-receipt"><b>Propuesta importada.</b><p>${missing.length?'Falta revisar: '+escape(missing.join(', ')):'La propuesta quedó lista para el siguiente paso.'}</p></div>`;f.elements.package.value='';f.elements.reviewed.checked=false;await detail(active);await refresh();message('Propuesta importada. Semblanzia realizó el registro interno automáticamente.');}));});
 if($('#comparison'))$('#comparison').addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget,x=new FormData(f);run(()=>lock(f,()=>action('comparison',{quote_ids:x.getAll('quote_ids'),note:x.get('note'),publish:f.elements.publish.checked})));});
 $('#detail').querySelectorAll('[data-publish]').forEach(b=>b.addEventListener('click',()=>run(()=>action('publish_comparison',{comparison_id:b.dataset.publish}))));
}
$('#login').addEventListener('submit',e=>{e.preventDefault();run(()=>lock(e.currentTarget,async()=>{const x=formData(e.currentTarget);const {error}=await client.auth.signInWithPassword(x);if(error)throw error;await session();}));});
if($('#signup'))$('#signup').addEventListener('click',()=>run(async()=>{const f=$('#login');if(!f.reportValidity())return;const {data,error}=await client.auth.signUp({...formData(f),options:{emailRedirectTo:new URL('../account/?planea=1',location.href).href}});if(error)throw error;if(data.session)await session();else message('Revisa tu correo para confirmar tu cuenta. Después podrás iniciar sesión aquí.');}));
$('#signout').addEventListener('click',()=>run(async()=>{await client.auth.signOut();location.reload();}));$('#refresh').addEventListener('click',()=>run(async()=>{await refresh();if(active)await detail(active);}));
if($('#intake'))$('#intake').addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget,x=formData(f);if(x.service_category==='Otro'){x.service_category=String(x.service_category_other||'').trim();if(!x.service_category)throw new Error('Escribe el servicio que necesitas.');}delete x.service_category_other;for(const k of ['budget_min','budget_max']){if(x[k]==='')delete x[k];else x[k]=Number(x[k]);}const retry=keyFor('intake',x);run(()=>lock(f,async()=>{const event=new URLSearchParams(location.search).get('event');const id=await rpc('planea_submit_request',{p_data:x,p_key:retry.key,p_event:event||null});retryKeys.delete(retry.fingerprint);f.reset();if(serviceSelect&&serviceOther){serviceOther.hidden=true;serviceOther.required=false;}await refresh();await detail(id);message('Recibimos tu solicitud. Aquí podrás seguir su avance.');}));});
async function session(){const {data,error}=await client.auth.getSession();if(error)throw error;const signed=!!data.session;$('#auth').hidden=signed;$('#signout').hidden=!signed;if(operator){$('#operator').hidden=true;if(signed){if(!await rpc('planea_operator_status',{}))throw new Error('Tu cuenta no está autorizada para operar PLANEA.');$('#operator').hidden=false;await refresh();}}else{$('#customer').hidden=!signed;if(signed)await refresh();}}
run(session);
})();
